package ro.gabrielbadicioiu.progressivemaintenance.feature_profileScreen.presentation

import android.net.Uri

sealed class ProfileScreenEvent {
    data object OnNavigateHome:ProfileScreenEvent()
    data object OnNavigateToMembers:ProfileScreenEvent()
    data object OnGetLoggedUser:ProfileScreenEvent()
    data object OnAddProductionLineClick:ProfileScreenEvent()
    data object OnShowOtpClick:ProfileScreenEvent()
    data object OnUserTabClick:ProfileScreenEvent()
    data object OnCompanyTabClick:ProfileScreenEvent()
    data object OnEditFirstNameClick:ProfileScreenEvent()
    data object OnCancelFirstNameEditClick:ProfileScreenEvent()
    data object OnDoneEditFirstNameClick:ProfileScreenEvent()
    data object OnEditLastNameClick:ProfileScreenEvent()
    data object OnEditLastNameCancelClick:ProfileScreenEvent()
    data object OnDoneEditLastName:ProfileScreenEvent()
    data object OnLogoutClick:ProfileScreenEvent()
    data object OnOpenSheet:ProfileScreenEvent()
    data object OnCloseSheet:ProfileScreenEvent()
    data object OnShowOldPass:ProfileScreenEvent()
    data object OnShowNewPass:ProfileScreenEvent()
    data object OnShowConfNewPass:ProfileScreenEvent()
    data object OnConfirmPassChange:ProfileScreenEvent()
    data object OnUpdateUserPass:ProfileScreenEvent()
    data object OnEditOrganisationNameClick:ProfileScreenEvent()
    data object OnEditOrganisationNameCancel:ProfileScreenEvent()
    data object OnEditingOrganisationNameConfirm:ProfileScreenEvent()
    data object OnEditOrganisationDomain:ProfileScreenEvent()
    data object OnEditOrganisationDomainCancel:ProfileScreenEvent()
    data object OnOrganisationDomainEditConfirm:ProfileScreenEvent()

    data class OnGetArgumentData(val companyId:String, val userId:String):ProfileScreenEvent()
    data class OnProfileUriResult(val uri: Uri?):ProfileScreenEvent()
    data class OnCompanyLogoUriResult(val uri:Uri?):ProfileScreenEvent()
    data class OnAnimateScrollToPage(val page:Int):ProfileScreenEvent()
    data class OnUpdateCompany(val update:String):ProfileScreenEvent()
    data class OnUpdateUser(val update:String):ProfileScreenEvent()
    data class OnFirstNameChange(val fistName:String):ProfileScreenEvent()
    data class OnLastNameChange(val lastName:String):ProfileScreenEvent()
    data class OnOldPassChange(val oldPass:String):ProfileScreenEvent()
    data class OnNewPassChange(val newPass:String):ProfileScreenEvent()
    data class OnConfNewPassChange(val confNewPass:String):ProfileScreenEvent()
    data class OnOrganisationNameChange(val organisationName:String):ProfileScreenEvent()
    data class OnOrganisationDomainChange(val organisationDomain:String):ProfileScreenEvent()
}